import os
import sqlite3
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib.backends.backend_pdf import PdfPages
from datetime import datetime

def generate_reports(db_path="data/processed/cricket_intelligence.db", output_dir="reports"):
    """
    Generates PDF, Excel, and CSV reports containing Player Rankings,
    Venue Insights, ML Predictions, and Recommendations.
    """
    os.makedirs(output_dir, exist_ok=True)
    
    if not os.path.exists(db_path):
        raise FileNotFoundError(f"Database not found at {db_path}.")
        
    conn = sqlite3.connect(db_path)
    
    # Load data
    rankings_df = pd.read_sql("SELECT * FROM player_overall_metrics ORDER BY cpis_rating DESC", conn)
    venue_insights_df = pd.read_sql("SELECT * FROM player_venue_insights", conn)
    predictions_df = pd.read_sql("SELECT * FROM player_predictions ORDER BY rating_predicted_2026 DESC", conn)
    
    conn.close()
    
    # ------------------ 1. EXPORT CSV & EXCEL ------------------
    csv_path = f"{output_dir}/player_rankings_top100.csv"
    print(f"Exporting Top 100 CSV to {csv_path}...")
    rankings_df.head(100).to_csv(csv_path, index=False)
    
    xlsx_path = f"{output_dir}/player_intelligence_report.xlsx"
    print(f"Exporting Multi-Sheet Excel to {xlsx_path}...")
    with pd.ExcelWriter(xlsx_path, engine="openpyxl") as writer:
        rankings_df.to_excel(writer, sheet_name="Player Rankings", index=False)
        venue_insights_df.to_excel(writer, sheet_name="Venue Insights", index=False)
        predictions_df.to_excel(writer, sheet_name="Player Predictions", index=False)
        
    # ------------------ 2. GENERATE PDF REPORT ------------------
    pdf_path = f"{output_dir}/player_intelligence_report.pdf"
    print(f"Generating Visual PDF Report at {pdf_path}...")
    
    # Set plot style for premium dark-navy themed visuals
    plt.rcParams["font.family"] = "sans-serif"
    plt.rcParams["text.color"] = "#0F172A"
    
    with PdfPages(pdf_path) as pdf:
        # ------------------ PAGE 1: Executive Summary & Rankings ------------------
        fig, axes = plt.subplots(2, 1, figsize=(8.5, 11), gridspec_kw={'height_ratios': [1, 2]})
        fig.patch.set_facecolor('#F8FAFC')
        
        # Header / Title Block
        ax_title = axes[0]
        ax_title.axis("off")
        ax_title.set_facecolor('#F8FAFC')
        
        # Draw a custom background box for the header
        rect = plt.Rectangle((0, 0.4), 1, 0.5, facecolor='#1E293B', transform=ax_title.transAxes, zorder=0)
        ax_title.add_patch(rect)
        
        ax_title.text(0.5, 0.7, "CRICKET PERFORMANCE INTELLIGENCE SYSTEM", 
                     fontsize=18, fontweight="bold", color="white", ha="center", va="center", transform=ax_title.transAxes)
        ax_title.text(0.5, 0.5, "Executive Player Intelligence Report", 
                     fontsize=14, color="#38BDF8", ha="center", va="center", transform=ax_title.transAxes)
        ax_title.text(0.95, 0.45, f"Date: {datetime.now().strftime('%Y-%m-%d')}", 
                     fontsize=9, color="#94A3B8", ha="right", va="center", transform=ax_title.transAxes)
        
        # Executive Summary Text
        summary_text = (
            "EXECUTIVE SUMMARY:\n"
            "This report outlines the player ratings generated by the CPIS composite ranking framework. "
            "Player Match Impact Scores (MIS), Consistency Indices (CI), and Pressure Performance Indices (PPI) "
            "were aggregated over 5 seasons of T20 league match data. Mixed-integer linear programming is utilized "
            "to calculate optimal lineups, and machine learning models are deployed to forecast 2026 season stats."
        )
        ax_title.text(0.05, 0.1, summary_text, fontsize=9.5, style="italic", color="#334155", 
                     wrap=True, ha="left", va="center", transform=ax_title.transAxes)
        
        # Top 10 Table
        ax_table = axes[1]
        ax_table.axis("off")
        ax_table.text(0.0, 1.02, "Top 10 Player Rankings (CPIS composite score)", 
                     fontsize=12, fontweight="bold", color="#1E293B", transform=ax_table.transAxes)
        
        # Extract Top 10 columns for report
        top_10 = rankings_df.head(10)[["rank", "player", "role", "matches", "match_impact_score", "consistency_index", "pressure_performance_index", "cpis_rating"]].copy()
        top_10.columns = ["Rank", "Player", "Role", "Matches", "MIS", "Consistency", "Pressure", "CPIS Rating"]
        
        # Format columns
        top_10["MIS"] = top_10["MIS"].round(1)
        top_10["Consistency"] = top_10["Consistency"].round(1)
        top_10["Pressure"] = top_10["Pressure"].round(1)
        
        # Draw table
        cell_text = top_10.values
        col_labels = top_10.columns
        table = ax_table.table(cellText=cell_text, colLabels=col_labels, loc="upper center", cellLoc="center")
        table.auto_set_font_size(False)
        table.set_fontsize(8)
        table.scale(1.0, 1.6)
        
        # Format table headers
        for (row, col), cell in table.get_celld().items():
            if row == 0:
                cell.set_text_props(weight="bold", color="white")
                cell.set_facecolor("#1E293B")
            elif row % 2 == 0:
                cell.set_facecolor("#F1F5F9")
            else:
                cell.set_facecolor("white")
                
        # Draw rating distribution plot in empty space
        # Let's adjust heights to fit a third small ax
        plt.tight_layout()
        pdf.savefig(fig)
        plt.close()
        
        # ------------------ PAGE 2: Venue Insights & ML Predictions ------------------
        fig2, axes2 = plt.subplots(2, 1, figsize=(8.5, 11))
        fig2.patch.set_facecolor('#F8FAFC')
        
        # Top 5 Predictions
        ax_pred = axes2[0]
        ax_pred.axis("off")
        ax_pred.text(0.0, 1.02, "ML Predictions: Top 5 Predicted Ratings for Upcoming Season (2026)", 
                     fontsize=12, fontweight="bold", color="#1E293B", transform=ax_pred.transAxes)
        
        top_pred = predictions_df.head(5)[["player", "rating_actual_2025", "rating_predicted_2026", "runs_actual_2025", "runs_predicted_2026", "wickets_actual_2025", "wickets_predicted_2026"]].copy()
        top_pred.columns = ["Player", "Rating (2025)", "Rating (2026 Prediction)", "Runs (2025)", "Runs (2026 Prediction)", "Wickets (2025)", "Wickets (2026 Prediction)"]
        
        table_pred = ax_pred.table(cellText=top_pred.values, colLabels=top_pred.columns, loc="upper center", cellLoc="center")
        table_pred.auto_set_font_size(False)
        table_pred.set_fontsize(8)
        table_pred.scale(1.0, 1.6)
        
        for (row, col), cell in table_pred.get_celld().items():
            if row == 0:
                cell.set_text_props(weight="bold", color="white")
                cell.set_facecolor("#0F766E") # Teal header
            elif row % 2 == 0:
                cell.set_facecolor("#F0FDFA")
            else:
                cell.set_facecolor("white")
                
        # Venue Recommendations
        ax_venue = axes2[1]
        ax_venue.axis("off")
        ax_venue.text(0.0, 0.95, "Key Player Recommendations & Venue Insights", 
                     fontsize=12, fontweight="bold", color="#1E293B", transform=ax_venue.transAxes)
        
        # Pull 3 sample player venue recommendations
        rec_texts = []
        sample_players = ["Virat Kohli", "Jasprit Bumrah", "Faf du Plessis"]
        for p in sample_players:
            p_rec = venue_insights_df[venue_insights_df["player"] == p]
            if len(p_rec) > 0:
                rec_texts.append(f"• {p}: {p_rec.iloc[0]['recommendation']}")
            else:
                rec_texts.append(f"• {p}: Recommend playing as core player at best-rated venues.")
                
        recommendations_block = "\n\n".join(rec_texts)
        ax_venue.text(0.0, 0.4, recommendations_block, fontsize=9.5, color="#334155", 
                     wrap=True, ha="left", va="center", transform=ax_venue.transAxes)
        
        # Add a footer note
        ax_venue.text(0.5, 0.05, "Confidential - CPIS Sports Analytics Division © 2026", 
                     fontsize=8, color="#94A3B8", ha="center", va="center", transform=ax_venue.transAxes)
        
        plt.tight_layout()
        pdf.savefig(fig2)
        plt.close()
        
    print(f"Report Generation Successful. Output documents located in {output_dir}/")
    return True

if __name__ == "__main__":
    generate_reports()
